### ISSUE TITLE
Docker Installation Issue

### ISSUE THREAD

**Issue by beefhotpot** [noerw/ttn-ogcswe-integration#7]
Hello!

Not sure if there's still anyone maintaining this implementation, but It would be great if someone can help me with problems occurred during my installation.

I followed the docker installation guide, and have done all the configuration. Everything went smooth until I used the `docker-compose up` command. 

```
docker_postgres_1 is up-to-date
docker_sos_1 is up-to-date
docker_proxy_1 is up-to-date
docker_ttn-integration_1 is up-to-date
Attaching to docker_postgres_1, docker_sos_1, docker_proxy_1, docker_ttn-integration_1
```

Then postgres is activated successfully
sos_1 is activated successfully despite some warning msg
proxy_1 seems to be fine ( I don't have a domain so I deleted the caddyfile part in `docker-compose.yml`)
However, ttn_integration_1 seems to fail in installation, following is the message I got:

```
ttn-integration_1  |
ttn-integration_1  | > ttn-ogcswe-integration@1.0.1 start /usr/src/app
ttn-integration_1  | > node dist/index.js
ttn-integration_1  |
ttn-integration_1  | module.js:597
ttn-integration_1  |   return process.dlopen(module, path._makeLong(filename));
ttn-integration_1  |                  ^
ttn-integration_1  |
ttn-integration_1  | Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64/grpc_node.node)
ttn-integration_1  |     at Error (native)
ttn-integration_1  |     at Object.Module._extensions..node (module.js:597:18)
ttn-integration_1  |     at Module.load (module.js:487:32)
ttn-integration_1  |     at tryModuleLoad (module.js:446:12)
ttn-integration_1  |     at Function.Module._load (module.js:438:3)
ttn-integration_1  |     at Module.require (module.js:497:17)
ttn-integration_1  |     at require (internal/module.js:20:19)
ttn-integration_1  |     at Object.<anonymous> (/usr/src/app/node_modules/grpc/src/node/src/grpc_extension.js:30:15)
ttn-integration_1  |     at Module._compile (module.js:570:32)
ttn-integration_1  |     at Object.Module._extensions..js (module.js:579:10)
ttn-integration_1  |
ttn-integration_1  | npm ERR! Linux 4.14.79-boot2docker
ttn-integration_1  | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
ttn-integration_1  | npm ERR! node v6.12.0
ttn-integration_1  | npm ERR! npm  v3.10.10
ttn-integration_1  | npm ERR! code ELIFECYCLE
ttn-integration_1  | npm ERR! ttn-ogcswe-integration@1.0.1 start: `node dist/index.js`
ttn-integration_1  | npm ERR! Exit status 1
ttn-integration_1  | npm ERR!
ttn-integration_1  | npm ERR! Failed at the ttn-ogcswe-integration@1.0.1 start script 'node dist/index.js'.
ttn-integration_1  | npm ERR! Make sure you have the latest version of node.js and npm installed.
ttn-integration_1  | npm ERR! If you do, this is most likely a problem with the ttn-ogcswe-integration package,
ttn-integration_1  | npm ERR! not with npm itself.
ttn-integration_1  | npm ERR! Tell the author that this fails on your system:
ttn-integration_1  | npm ERR!     node dist/index.js
ttn-integration_1  | npm ERR! You can get information on how to open an issue for this project with:
ttn-integration_1  | npm ERR!     npm bugs ttn-ogcswe-integration
ttn-integration_1  | npm ERR! Or if that isn't available, you can get their info via:
ttn-integration_1  | npm ERR!     npm owner ls ttn-ogcswe-integration
ttn-integration_1  | npm ERR! There is likely additional logging output above.
ttn-integration_1  |
ttn-integration_1  | npm ERR! Please include the following file with any support request:
ttn-integration_1  | npm ERR!     /usr/src/app/npm-debug.log
docker_ttn-integration_1 exited with code 1
```

My node and npm version are all the latest, so I'm not sure why I got errors like this. Maybe it's the problem with the package itself (like stated in the npm feedback above)? Hopefully someone can answer! Merry Christmas BTW.

Thanks

**Comment by noerw** [comment]
This looks like a docker build problem and is unrelated to your installed node version.
(And you guessed right, this repo is not actively maintained.)
I will try to look into it after the holidays.

**Comment by beefhotpot** [comment]
Thx noerw! Wish you a good holiday!

**Comment by noerw** [comment]
The issue was an error in the docker build, because of an incompatibility of the C++ inside the container with a dependency of this application.
When upgrading all the dependencies, this issue was resolved. Thanks for pointing me to it!
An updated docker image `noerw/ttn-ogcswe-integration:latest` is currently being built and should be available soon.

As mentioned, I didn't do maintenance on this tool for quite a while, so please let me know if other issues occur.
Also good holidays to you!

**Comment by beefhotpot** [comment]
Hi Noerw,
Thanks for your work in updating this repository!
Not sure if this matters but I found out that the docker image is still not the latest (created 15 months) and I got the same error if I'm following the docker building way.
The native installation way seems to work fine though.

**Comment by noerw** [comment]
[According to docker hub](https://hub.docker.com/r/noerw/ttn-ogcswe-integration/builds), the new image was successfully built.
Are you sure you pulled the latest version and recreated your container?
e.g. `docker-compose pull && docker-compose up --force-recreate`

**Comment by beefhotpot** [comment]
Hi norwin,
Like you said, I recreated the container.
But the error in creating ttn-integration still remains:

```
ttn-integration_1  |
ttn-integration_1  | > ttn-ogcswe-integration@1.0.1 start /usr/src/app
ttn-integration_1  | > node dist/index.js
ttn-integration_1  |
ttn-integration_1  | bridge configuration is invalid or missing: Error:
EISDIR: illegal operation on a directory, read
ttn-integration_1  | npm ERR! code ELIFECYCLE
ttn-integration_1  | npm ERR! errno 1
ttn-integration_1  | npm ERR! ttn-ogcswe-integration@1.0.1 start: `node
dist/index.js`
ttn-integration_1  | npm ERR! Exit status 1
ttn-integration_1  | npm ERR!
ttn-integration_1  | npm ERR! Failed at the ttn-ogcswe-integration@1.0.1
start script.
ttn-integration_1  | npm ERR! This is probably not a problem with npm.
There is likely additional logging output above.
ttn-integration_1  |
ttn-integration_1  | npm ERR! A complete log of this run can be found in:
ttn-integration_1  | npm ERR!
 /root/.npm/_logs/2019-01-22T06_08_22_684Z-debug.log
docker_ttn-integration_1 exited with code 1
```

thansk

**Comment by noerw** [comment]
This is a different error message: `bridge configuration is invalid or missing: Error: EISDIR: illegal operation on a directory, read`.
It seems you don't have the configuration file inside the container or a folder with the name `config.yml`..
